spring.application.name=srsyduts-backend

# Tell Spring Boot to look for a secrets file alongside this one
spring.config.import=optional:file:./src/main/resources/application-secrets.properties

logging.level.org.springframework.security=TRACE